app/Http/routes.php
<?php

Route::get('instal', 'ConfigController@index');

Route::get('/', function () {
    return view('welcome');
});
Route::get('/homes', function () {
    return view('home');
});

Route::post('/storeurl', 'ConfigController@store');

Route::group(['middleware' => 'config'], function () {
	
	Route::get('/', function () {
	    return view('welcome');
	});

	Route::get('/homes', function () {
	    return view('home');
	});

	Route::get('/home', 'ProjectController@index');

	Route::auth();

	Route::resource('/project', 'ProjectController');

	Route::get('/path/{id}', 'PathController@index1');

	Route::get('/path/addpath/{id}', 'PathController@create');

	Route::post('/storepath/{id}', 'PathController@store');

	Route::get('/showpath/{id}', 'PathController@show');

	Route::get('/editpath/{id}', 'PathController@edit');

	Route::post('/updatepath/{id}', 'PathController@update');

	Route::delete('/destroypath/{id}', 'PathController@destroy');
});

Route::post('/registerapi', 'ApiController@registerapi');

Route::post('/loginapi', 'ApiController@loginapi');

Route::group(['middleware' => 'jwt-auth'], function () {

	Route::post('/get_user_details1', 'ApiController@get_user_details');
	
	Route::get('/{project?}/{endpoint?}','ApiController@makeApi');
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $table = 'project';
    protected $primaryKey = 'id';
    protected $fillable = ['name',
    						'client',
    						'user'];
    public $timestamps = false;
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use Auth;

use App\Project;

use App\Path;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');        
    }
    
    public function index()
    {
        $id_user=Auth::User()->id;
        $datas = Project::where('id_user',$id_user)->orderBy('id','DESC')->paginate(10);
        return view('projects.project')->with('datas',$datas);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('projects.addproject');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
        'name'=>'required',
        'client'=>'required',
        'user'=>'required',    
        ]);

        $project = new project;
        $project->id_user=Auth::User()->id;
        $project->name=$request->name;
        $project->client=$request->client;
        $project->user=$request->user;
        $project->save();
        
        return redirect()->route('project.index')->with('alert-success','Data Has been Saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect()->to('/path/'.$id)->with('id',$id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $project = Project::where('id', $id)->first();
        return view('projects.editproject',compact('project'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
        'name'=>'required',
        'client'=>'required',
        'user'=>'required',    
        ]);

        $project = Project::where('id', $id)->first();
        $project->name=$request->name;
        $project->client=$request->client;
        $project->user=$request->user;
        $project->save();
        
        return redirect()->route('project.index')->with('alert-success','Data Has been Updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $hapus = Project::find($id);
        $hapus->delete();

        return redirect()->route('project.index')->with('alert-success','Data Has been Deleted!');
    }
}

resources/views/projects/addproject.blade.php
@extends('layouts.template_user')

@section('content')

<div class="body-wrapper">
	<nav id="menu" class="menu">
	    <ul id="tiny">
	        <li class="active"><a href="{{ url('/home') }}"><i class="fa fa-cubes" aria-hidden="true"></i> Project</a>
	        </li>
	        <li><a href="{{ url('/logout') }}"><i class="fa fa-sign-out" aria-hideen="true"></i> Logout</a>
	        </li>    
	    </ul>
	</nav>
	  <!-- /.menu -->
	  
	  <div class="box box-border pull-left">
	    <div class="light-wrapper">
	      	<div class="container inner">
		      	<div class="row login">
			        <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 well">
			            <form role="form" action="{{route('project.store')}}" method="post" enctype="multipart/form-data">
			            {{ csrf_field() }}
				             <div class="form-group text-center">
				                <div class="logo">
				                    <span><img src="http://cdn.dev.classmethod.jp/wp-content/uploads/2014/05/aws_icon_vpc.png" style="height: 200px;width: 200px"></span>
				                </div>
				            </div>
				            <div class="form-group">
				                <input type="text" name="name" class="form-control input-lg" id="projectname" placeholder="Project name">
				                {!! $errors->first('name','<p class="help-block">:message</p>') !!}
				            </div>
				            <div class="form-group">
				                <input type="text" name="client" class="form-control input-lg" id="clientname" placeholder="Client">
				                {!! $errors->first('client','<p class="help-block">:message</p>') !!}
				            </div>
				            <div>
				                <input type="text" name="user" class="form-control input-lg" placeholder="Username">
				                {!! $errors->first('user','<p class="help-block">:message</p>') !!}
				            </div>
				            <div class="form-group" style="margin-bottom: 15px">
				                <button type="submit" class="btn btn-default btn-lg btn-block btn-success">Save</button>
				            </div>
				            <div class="form-group">
				                <a class="btn btn-default btn-lg btn-block btn-success" href="{{ url('/home') }}">Cancel</a>
				            </div>
			            </form>
			        </div>
		    	</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/projects/editproject.blade.php
@extends('layouts.template_user')

@section('content')

<div class="body-wrapper">
	<nav id="menu" class="menu">
	    <ul id="tiny">
	        <li class="active"><a href="{{ url('/home') }}"><i class="fa fa-cubes" aria-hidden="true"></i> Project</a>
	        </li>
	        <li><a href="{{ url('/logout') }}"><i class="fa fa-sign-out" aria-hideen="true"></i> Logout</a>
	        </li>    
	    </ul>
	</nav>
	  <!-- /.menu -->
	  
	  <div class="box box-border pull-left">
	    <div class="light-wrapper">
	      	<div class="container inner">
		      	<div class="row login">
			        <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 well">
			            <form role="form" action="{{route('project.update',$project->id)}}" method="post" enctype="multipart/form-data">
			            <input name="_method" type="hidden" value="PATCH">
						{{ csrf_field() }}
				             <div class="form-group text-center">
				                <div class="logo">
				                    <span><img src="http://cdn.dev.classmethod.jp/wp-content/uploads/2014/05/aws_icon_vpc.png" style="height: 200px;width: 200px"></span>
				                </div>
				            </div>
				            <div class="form-group">
				                <input type="text" name="name" class="form-control input-lg" id="projectname" placeholder="Project name" value="{{ $project->name }}">
				                {!! $errors->first('name','<p class="help-block">:message</p>') !!}
				            </div>
				            <div class="form-group">
				                <input type="text" name="client" class="form-control input-lg" id="clientname" placeholder="Client" value="{{ $project->client }}">
				                {!! $errors->first('client','<p class="help-block">:message</p>') !!}
				            </div>
				            <div>
				                <input type="text" name="user" class="form-control input-lg" placeholder="Username" value="{{ $project->user }}">
				                {!! $errors->first('user','<p class="help-block">:message</p>') !!}
				            </div>
				            <div class="form-group" style="margin-bottom: 15px">
				                <button type="submit" class="btn btn-default btn-lg btn-block btn-success">Save</button>
				            </div>
				            <div class="form-group">
				                <a class="btn btn-default btn-lg btn-block btn-success" href="{{ url('/home') }}">Cancel</a>
				            </div>
			            </form>
			        </div>
		    	</div>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/projects/project.blade.php
@extends('layouts.app')

@section('content')
<nav id="menu" class="menu">
    <ul id="tiny">
        <li class="active"><a href="{{ url('/home') }}"><i class="fa fa-cubes" aria-hidden="true"></i> Project</a>
        </li>
        <li><a href="{{ url('/logout') }}"><i class="fa fa-sign-out" aria-hideen="true"></i> Logout</a>
        </li>    
    </ul>
</nav>

<div class="box box-border pull-left">
    <div class="light-wrapper">
        <div class="container inner">
            <div class="row">
                <h2 class="text-center" style="text-align: left !important;
                padding-left: 50px;
                padding-bottom: 20px;
                margin-top: -30px;">Project</h2>
                <div class="col-md-9"></div>
                <a class="btn btn-success" style="margin-bottom: 20px" href="{{route('project.create')}}">Add Project</a>
            </div>

            <div class="row">
                <div class="col-md-10" style="margin-left: 32px">
                    <table id="datatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>Project Name</th>
                                <th>Client</th>
                                <th>Username</th>
                                <th>Edit</th>
                                <th>Delete</th>
                                <th>See The Path</th>
                            </tr>
                        </thead>

                        <tfoot>
                            <tr>
                                <th>Project Name</th>
                                <th>Client</th>
                                <th>Username</th>
                                <th>Edit</th>
                                <th>Delete</th>
                                <th>See The Path</th>
                            </tr>
                        </tfoot>

                        <tbody>
                        @foreach($datas as $data)
                            <tr>
                                <td>{{$data->name}}</td>
                                <td>{{$data->client}}</td>
                                <td>{{$data->user}}</td>
                                <td>
                                    <p data-placement="top" data-toggle="tooltip" title="Edit">
                                        <a class="btn btn-primary btn-xs" data-title="Edit" href="{{route('project.edit',$data->id)}}"><span class="glyphicon glyphicon-pencil"></span></a>
                                    </p>
                                </td>
                                <td>
                                    <form class="" action="{{route('project.destroy',$data->id)}}" method="post">
                                        <a class="btn btn-danger btn-xs" data-title="Delete" type="submit" onclick="return confirm('are you sure to delete this data??');" value="delete"><span class="glyphicon glyphicon-trash"></span></a>
                                    </form>
                                </td>
                                <td>
                                    <p data-placement="top" data-toggle="tooltip" title="Edit">
                                        <a href="{{route('project.show',$data->id)}}"><button class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit"><i class="fa fa-eye" aria-hidden="true"></i>
                                        </button></a>
                                    </p>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection